# Generated by Django 5.1.6 on 2025-04-29 12:03

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_interests_student_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Criminology', 'Criminology'), ('Information technology', 'Information technology'), ('Accountancy', 'Accountancy'), ('Early Childhood Education', 'Early Childhood Education'), ('Journalism', 'Journalism'), ('Elementary Education', 'Elementary Education'), ('Secondary Education Major in English', 'Secondary Education Major in English'), ('Secondary Education Major in Mathematics', 'Secondary Education Major in Mathematics'), ('Secondary Education Major in Social Studies', 'Secondary Education Major in Social Studies'), ('Political Science', 'Political Science'), ('Public Administration', 'Public Administration'), ('Social Work', 'Social Work'), ('Business Administration Major in Financial Management', 'Business Administration Major in Financial Management'), ('Business Administration Major in Human Resource Management', 'Business Administration Major in Human Resource Management'), ('Business Administration Major in Marketing Management', 'Business Administration Major in Marketing Management'), ('Management Accounting', 'Management Accounting')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Accounting', 'Accounting'), ('Advertising', 'Advertising'), ('Branding', 'Branding'), ('Business', 'Business'), ('Business Strategy', 'Business Strategy'), ('Child Development', 'Child Development'), ('Coding', 'Coding'), ('Community Service', 'Community Service'), ('Consumer Behavior', 'Consumer Behavior'), ('Counseling', 'Counseling'), ('Debating', 'Debating'), ('Drawing', 'Drawing'), ('Economics', 'Economics'), ('Entrepreneurship', 'Entrepreneurship'), ('Finance', 'Finance'), ('Fitness', 'Fitness'), ('Gaming', 'Gaming'), ('Geography', 'Geography'), ('History', 'History'), ('Human Rights', 'Human Rights'), ('Investment', 'Investment'), ('Journalism', 'Journalism'), ('Law', 'Law'), ('Leadership', 'Leadership'), ('Math', 'Math'), ('Music', 'Music'), ('Negotiation', 'Negotiation'), ('Painting', 'Painting'), ('Philosophy', 'Philosophy'), ('Photography', 'Photography'), ('Politics', 'Politics'), ('Psychology', 'Psychology'), ('Reading', 'Reading'), ('Robotics', 'Robotics'), ('Social Justice', 'Social Justice'), ('Social Media', 'Social Media'), ('Social Skills', 'Social Skills'), ('Social Work', 'Social Work'), ('Statistics', 'Statistics'), ('Teaching', 'Teaching'), ('Technology', 'Technology'), ('Traveling', 'Traveling'), ('Writing', 'Writing')], help_text='Select up to 3 interests.', max_length=460, null=True),
        ),
    ]
